steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    arg: ['installs']

  # Test
  - name: 'gcr.io/cloud-builders/npm'
    arg: ['run', 'test:unit']

  # Build
  - name: 'gcr.io/cloud-builders/npm'
    arg: ['run', 'build']

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    arg: ['deploy']
