
//userReducers Actions
export const SET_USER = 'SET_USER';
export const PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

//commentsReducer Actions
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const COMMENT_DELETION_SUCCESS = 'COMMENT_DELETION_SUCCESS';
export const COMMENT_DELETION_ERROR = 'COMMENT_DELETION_ERROR';

//createPostReducer Actions
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const UPLOAD_POST_IMAGE_SUCCESS = 'UPLOAD_POST_IMAGE_SUCCESS';
export const UPLOAD_POST_IMAGE_FAILED = 'UPLOAD_POST_IMAGE_FAILED';

//uiReducer Actions
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';